project_id = "ystnsszlaqhwysgptysd"

[functions.delete-user]
verify_jwt = true

[functions.create-founder]
verify_jwt = true

[functions.reset-founder]
verify_jwt = true

[functions.create-test-user]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = true

[functions.send-invitation-notification]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = true

[functions.approve-invitation]
verify_jwt = true

[functions.verify-inviter-email]
verify_jwt = false

[functions.create-invitation-request]
verify_jwt = false

[functions.send-friendship-notification]
verify_jwt = true

[functions.notify-wanted-ticket-matches]
verify_jwt = true